### ISSUE TITLE
Alternate server at: http://www.feoh.org/1110

### ISSUE THREAD

**Issue by feoh** [n01se/1110#1]
The main server seems perma-broke.

I have set another instance up at http://www.feoh.org/1110 for anyone who wants to play with this.

**Comment by kanaka** [comment]
I put your server address in the title so it's easier to find.

Also, we made a bunch of fixes since then to the server and it's handling the load better now. It's still capped at 20 connections, but now that the Hacker News flood is over that doesn't seem to be a big issue.

**Comment by feoh** [comment]
Great! I updated my server to the latest as well.

FWIW 700 users connected to my instance.

This is a neat project, thanks!
-Chris

On Thu, Sep 27, 2012 at 12:00 PM, Joel Martin notifications@github.comwrote:

> I put your server address in the title so it's easier to find.
> 
> Also, we made a bunch of fixes since then to the server and it's handling
> the load better now. It's still capped at 20 connections, but now that the
> Hacker News flood is over that doesn't seem to be a big issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/n01se/1110/issues/1#issuecomment-8941352.

## 

Christopher Patti - Geek At Large | GTalk: cpatti@gmail.com | AIM:
chrisfeohpatti | P: (260) 54PATTI
"Technology challenges art, art inspires technology." - John Lasseter, Pixar
