### ISSUE TITLE
Server error with default .htaccess

### ISSUE THREAD

**Issue by CodingMinds** [n01se/1110#2]
The included .htaccess file in the images directory causes a server error within default apache installations

```
[Wed Sep 26 23:04:56 2012] [alert] [client 89.204.137.110] /var/www/1110.geek1.de/images/.htaccess: Invalid command 'Header', perhaps misspelled or defined by a module not included in the server configuration, referer: http://1110.geek1.de/
```

Also everyone need to edit this file to change the regex pattern to match the used (sub)domain.

I guess you should add a hint within the installation instructions and / or disable it by default.

**Comment by kanaka** [comment]
I've removed that. Originally we were trying to pull directly from xkcd, however, xkcd doesn't have cross-origin marked on the images so we can't anyways. I've removed the cross-origin stuff since we aren't using it and other servers should host their own images anyways.
